# for production
version: '3.7'
services:
  mes-courses:
    image: abcdevelop/simple-breath:0.0.1
    container_name: respire-simple_0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      target: 'production-stage'
    ports:
      - '8001:80'
    volumes:
      - '/app/node_modules'
      - '.:/app'
