# for production
version: '3.7'
services:
  mes-courses:
    image: abcdevelop/simple-breath:3
    container_name: simple-breath_3
    build:
      context: .
      dockerfile: Dockerfile
      target: 'production-stage'
    ports:
      - '8083:80'
    volumes:
      - '/app/node_modules'
      - '.:/app'
