# for production
version: '3.7'
services:
  mes-courses:
    image: abcdevelop/simple-breath:1.0.0
    container_name: simple-breath_1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: 'production-stage'
    ports:
      - '807O:80'
    volumes:
      - '/app/node_modules'
      - '.:/app'
